TERMUX_PKG_HOMEPAGE=https://github.com/PWN-Term/john
TERMUX_PKG_DESCRIPTION="John the Ripper jumbo - advanced offline password cracker, which supports hundreds of hash and cipher types, and runs on many operating systems, CPUs, GPUs, and even some FPGAs"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER=@hilledkinged
TERMUX_PKG_VERSION=15.08.21
TERMUX_PKG_REVISION=2
TERMUX_PKG_DEPENDS="openssl"
TERMUX_PKG_SRCURL=https://github.com/PWN-Term/john/releases/download/pwn/massage.tar.gz
TERMUX_PKG_SHA256=18e7fc2b374fc7992e76b6a67baeb145140c356b0204bee0a4f2bf6b6a677b02
TERMUX_PKG_BUILD_IN_SRC=true
PWN_SRC_STRIP=false
