TERMUX_PKG_HOMEPAGE=https://github.com/termux/libandroid-shmem
TERMUX_PKG_DESCRIPTION="System V shared memory emulation on Android using ashmem"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.3
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/PWN-Term/libandroid-shmem/archive/refs/heads/master.zip
TERMUX_PKG_SHA256=8acd8aaa85c2db50214d878e091d91c4fdf20907badbea4f27e18962a17a1962
TERMUX_PKG_BREAKS="libandroid-shmem-dev"
TERMUX_PKG_REPLACES="libandroid-shmem-dev"
TERMUX_PKG_BUILD_IN_SRC=true
